













# Jinja

[Jinja](https://docs.getdbt.com/docs/build/jinja-macros) in dbt is used to perform functions that regular SQL is unable to do, such as iterating over columns using a `for` loop and also `if` statements. Jinja is also used to hold environment variables which can be (re)used all over your project. A simple example of jinja use in dbt is when calling the `ref()` function. If you see anything with double curly brackets (`{{ }}`) or with brackets and percentage sign(s) in them (`{% %}`) then you are dealing with jinja.  

Let's start by explaining some jinja concepts.

- **Expressions {{ ... }}**: Expressions are used when you want to output a string. You can use expressions to reference variables and call macros.

- **Statements {% ... %}**: Statements don't output a string. They are used for control flow, for example, to set up for loops and if statements, to set or modify variables, or to define macros.

- **Comments {# ... #}**: Jinja comments are used to prevent the text within the comment from executing or outputing a string. Don't use -- for comment.


To make the point sink home since jinja can at time look mind boggling to the novice beginner, we'll start with explaining a for loop. This is the skeleton of a `for` loop in jinja.

```
{% for item in sequence %}
-- SQL Code for {{ item }}
{% endfor %}

```















